"""books: transaction VAT and import fingerprint

Revision ID: 0004_books
Revises: 0003_user_language
Create Date: 2026-09-24 17:58:49.200791
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0004_books'
down_revision: str | None = '0003_user_language'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('vat_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('external_id', sa.String(length=64), nullable=True))
    op.create_unique_constraint('uq_transactions_company_external', 'transactions', ['company_id', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transactions_company_external', 'transactions', type_='unique')
    op.drop_column('transactions', 'external_id')
    op.drop_column('transactions', 'vat_amount')
    # ### end Alembic commands ###
