"""rule reviews

Revision ID: 0005_reviews
Revises: 0004_books
Create Date: 2026-09-24 22:41:33.879014
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0005_reviews'
down_revision: str | None = '0004_books'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_kind', sa.String(length=16), nullable=False),
    sa.Column('item_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=24), nullable=False),
    sa.Column('notes', sa.String(length=4000), nullable=True),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('reviewer_name', sa.String(length=255), nullable=False),
    sa.Column('reviewer_credentials', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_reviews_item_id'), 'rule_reviews', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rule_reviews_item_id'), table_name='rule_reviews')
    op.drop_table('rule_reviews')
    # ### end Alembic commands ###
