"""reminders

Revision ID: 0006_reminders
Revises: 0005_reviews
Create Date: 2026-09-24 22:55:49.429858
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0006_reminders'
down_revision: str | None = '0005_reviews'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('deadline_key', sa.String(length=200), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', 'deadline_key', 'channel', name='uq_reminder_log_once')
    )
    op.create_index(op.f('ix_reminder_log_user_id'), 'reminder_log', ['user_id'], unique=False)
    op.add_column('users', sa.Column('reminder_email', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('reminder_days', sa.Integer(), server_default='3', nullable=False))
    op.add_column('users', sa.Column('telegram_chat_id', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('telegram_link_code', sa.String(length=32), nullable=True))
    op.create_unique_constraint('uq_users_telegram_link_code', 'users', ['telegram_link_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_telegram_link_code', 'users', type_='unique')
    op.drop_column('users', 'telegram_link_code')
    op.drop_column('users', 'telegram_chat_id')
    op.drop_column('users', 'reminder_days')
    op.drop_column('users', 'reminder_email')
    op.drop_index(op.f('ix_reminder_log_user_id'), table_name='reminder_log')
    op.drop_table('reminder_log')
    # ### end Alembic commands ###
