"""payments

Revision ID: 0008_payments
Revises: 0007_password_resets
Create Date: 2026-09-28 03:54:33.328649
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0008_payments'
down_revision: str | None = '0007_password_resets'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_banks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('bank_id', sa.String(length=32), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', name='uq_company_banks_company')
    )
    op.add_column('tax_events', sa.Column('paid_on', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tax_events', 'paid_on')
    op.drop_table('company_banks')
    # ### end Alembic commands ###
