"""rs and banks

Revision ID: 0009_rs_banks
Revises: 0008_payments
Create Date: 2026-09-28 04:41:59.798319
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0009_rs_banks'
down_revision: str | None = '0008_payments'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_rs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('service_user', sa.String(length=100), nullable=False),
    sa.Column('password_encrypted', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('registered_name', sa.String(length=255), nullable=True),
    sa.Column('vat_payer', sa.Boolean(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', name='uq_company_rs_company')
    )
    op.add_column('company_banks', sa.Column('currency', sa.String(length=3), server_default='GEL', nullable=False))
    op.add_column('company_banks', sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('company_banks', sa.Column('last_import_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('company_banks', sa.Column('last_import_count', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_company_banks_company'), 'company_banks', type_='unique')
    op.create_index(op.f('ix_company_banks_company_id'), 'company_banks', ['company_id'], unique=False)
    # ### end Alembic commands ###
    # Until now a company had at most one bank, the one taxes were paid from.
    op.execute("UPDATE company_banks SET is_primary = true")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_banks_company_id'), table_name='company_banks')
    op.create_unique_constraint(op.f('uq_company_banks_company'), 'company_banks', ['company_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('company_banks', 'last_import_count')
    op.drop_column('company_banks', 'last_import_at')
    op.drop_column('company_banks', 'is_primary')
    op.drop_column('company_banks', 'currency')
    op.drop_table('company_rs')
    # ### end Alembic commands ###
